<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="7" failed="4" total="16" passed="5">
  <reporter-output>
    <line>
      <![CDATA[this is our log]]>
    </line>
  </reporter-output>
  <suite name="Default Suite" duration-ms="3570" started-at="2018-12-24T12:48:52Z" finished-at="2018-12-24T12:48:55Z">
    <groups>
    </groups>
    <test name="com.test" duration-ms="3570" started-at="2018-12-24T12:48:52Z" finished-at="2018-12-24T12:48:55Z">
      <class name="TestDemo.CreateAccountTest">
        <test-method status="SKIP" signature="initializeTestBaseSetup(java.lang.String, java.lang.String)[pri:0, instance:TestDemo.CreateAccountTest@129a8472]" name="initializeTestBaseSetup" is-config="true" duration-ms="0" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeTestBaseSetup -->
        <test-method status="SKIP" signature="setUp()[pri:0, instance:TestDemo.CreateAccountTest@129a8472]" name="setUp" is-config="true" duration-ms="0" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="createAccountExample1()[pri:0, instance:TestDemo.CreateAccountTest@129a8472]" name="createAccountExample1" duration-ms="1" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAccountExample1 -->
        <test-method status="SKIP" signature="createAccountExample2()[pri:0, instance:TestDemo.CreateAccountTest@129a8472]" name="createAccountExample2" duration-ms="0" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAccountExample2 -->
        <test-method status="SKIP" signature="verifyCreateAnAccountPage()[pri:0, instance:TestDemo.CreateAccountTest@129a8472]" name="verifyCreateAnAccountPage" duration-ms="0" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCreateAnAccountPage -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:TestDemo.CreateAccountTest@129a8472]" name="tearDown" is-config="true" duration-ms="0" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestDemo.CreateAccountTest -->
      <class name="TestDemo.ExtentDemo">
        <test-method status="FAIL" signature="logDemo()[pri:0, instance:TestDemo.ExtentDemo@1b0375b3]" name="logDemo" duration-ms="1" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[our own exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: our own exception
	at TestDemo.ExtentDemo.logDemo(ExtentDemo.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
            <line>
              <![CDATA[this is our log]]>
            </line>
          </reporter-output>
        </test-method> <!-- logDemo -->
        <test-method status="FAIL" signature="test1()[pri:0, instance:TestDemo.ExtentDemo@1b0375b3]" name="test1" duration-ms="1" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at TestDemo.ExtentDemo.test1(ExtentDemo.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="PASS" signature="test2()[pri:0, instance:TestDemo.ExtentDemo@1b0375b3]" name="test2" duration-ms="1" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
      </class> <!-- TestDemo.ExtentDemo -->
      <class name="TestDemo.MySeleniumTest1">
        <test-method status="FAIL" signature="test03()[pri:0, instance:TestDemo.MySeleniumTest1@3cb5cdba]" name="test03" duration-ms="58" started-at="2018-12-24T20:48:52Z" finished-at="2018-12-24T20:48:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at TestDemo.MySeleniumTest1.test03(MySeleniumTest1.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test03 -->
        <test-method status="PASS" signature="rerunFailedCases()[pri:0, instance:TestDemo.MySeleniumTest1@3cb5cdba]" name="rerunFailedCases" is-config="true" duration-ms="1" started-at="2018-12-24T20:48:52Z" finished-at="2018-12-24T20:48:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rerunFailedCases -->
        <test-method status="FAIL" signature="test05()[pri:0, instance:TestDemo.MySeleniumTest1@3cb5cdba]" name="test05" duration-ms="1" started-at="2018-12-24T20:48:52Z" finished-at="2018-12-24T20:48:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at TestDemo.MySeleniumTest1.test05(MySeleniumTest1.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test05 -->
        <test-method status="PASS" signature="rerunFailedCases()[pri:0, instance:TestDemo.MySeleniumTest1@3cb5cdba]" name="rerunFailedCases" is-config="true" duration-ms="0" started-at="2018-12-24T20:48:52Z" finished-at="2018-12-24T20:48:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rerunFailedCases -->
        <test-method status="PASS" signature="testcase1()[pri:0, instance:TestDemo.MySeleniumTest1@3cb5cdba]" name="testcase1" duration-ms="3425" started-at="2018-12-24T20:48:52Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
        <test-method status="PASS" signature="rerunFailedCases()[pri:0, instance:TestDemo.MySeleniumTest1@3cb5cdba]" name="rerunFailedCases" is-config="true" duration-ms="0" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rerunFailedCases -->
        <test-method status="PASS" signature="rerunFailedCases()[pri:0, instance:TestDemo.MySeleniumTest1@3cb5cdba]" name="rerunFailedCases" is-config="true" duration-ms="0" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rerunFailedCases -->
        <test-method status="PASS" signature="testcase2()[pri:0, instance:TestDemo.MySeleniumTest1@3cb5cdba]" name="testcase2" duration-ms="0" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2 -->
        <test-method status="PASS" signature="test04()[pri:0, instance:TestDemo.MySeleniumTest1@3cb5cdba]" name="test04" duration-ms="1" started-at="2018-12-24T20:48:55Z" depends-on-methods="TestDemo.MySeleniumTest1.test05" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test04 -->
        <test-method status="PASS" signature="rerunFailedCases()[pri:0, instance:TestDemo.MySeleniumTest1@3cb5cdba]" name="rerunFailedCases" is-config="true" duration-ms="1" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rerunFailedCases -->
      </class> <!-- TestDemo.MySeleniumTest1 -->
      <class name="TestDemo.BasePageTest">
        <test-method status="FAIL" signature="initializeTestBaseSetup(java.lang.String, java.lang.String)[pri:0, instance:TestDemo.BasePageTest@d041cf]" name="initializeTestBaseSetup" is-config="true" duration-ms="0" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Parameter 'browserType' is required by @Configuration on method initializeTestBaseSetup but has not been marked @Optional or defined
in /Users/caomengmeng/Library/Caches/IntelliJIdea2018.3/temp-testng-customsuite.xml]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Parameter 'browserType' is required by @Configuration on method initializeTestBaseSetup but has not been marked @Optional or defined
in /Users/caomengmeng/Library/Caches/IntelliJIdea2018.3/temp-testng-customsuite.xml
	at org.testng.internal.Parameters.createParameters(Parameters.java:154)
	at org.testng.internal.Parameters.createParameters(Parameters.java:361)
	at org.testng.internal.Parameters.createConfigurationParameters(Parameters.java:84)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:201)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeTestBaseSetup -->
        <test-method status="SKIP" signature="setUp()[pri:0, instance:TestDemo.BasePageTest@d041cf]" name="setUp" is-config="true" duration-ms="0" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="baseTest1()[pri:0, instance:TestDemo.BasePageTest@d041cf]" name="baseTest1" duration-ms="0" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- baseTest1 -->
        <test-method status="SKIP" signature="baseTest2()[pri:0, instance:TestDemo.BasePageTest@d041cf]" name="baseTest2" duration-ms="1" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- baseTest2 -->
        <test-method status="SKIP" signature="verifyHomePage()[pri:0, instance:TestDemo.BasePageTest@d041cf]" name="verifyHomePage" duration-ms="1" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePage -->
        <test-method status="SKIP" signature="baseTest3()[pri:0, instance:TestDemo.BasePageTest@d041cf]" name="baseTest3" duration-ms="0" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- baseTest3 -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:TestDemo.BasePageTest@d041cf]" name="tearDown" is-config="true" duration-ms="0" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestDemo.BasePageTest -->
      <class name="TestDemo.AppTest">
        <test-method status="PASS" signature="shouldAnswerWithTrue()[pri:0, instance:TestDemo.AppTest@1134affc]" name="shouldAnswerWithTrue" duration-ms="0" started-at="2018-12-24T20:48:55Z" finished-at="2018-12-24T20:48:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shouldAnswerWithTrue -->
      </class> <!-- TestDemo.AppTest -->
    </test> <!-- com.test -->
  </suite> <!-- Default Suite -->
</testng-results>
